### PR TITLE
Fix placeholder positioned incorrectly

### PR DESCRIPTION
**Pull request by adeptds**
If two input fields positioned next to each other separated by a space - the placeholders are both placed in the first box.

### CODE REVIEW

**Comment by adeptds** [comment]
Needs more work / done differently - does not work correctly on window resize

**Comment by Fujilives** [comment]
I'm new at this whole github thing, so I apologize if I am doing this in the incorrect location - but I believe I have a fix that resolves all of the above / related problems ( I registered just to post it here )

In the javascript file where it says

```
// create the placeholder
$placeholder = $('<span>').addClass('placeholder').html(text);
```

I added these two lines directly above it (one is just a comment)

```
// create the div container for placeholder span to fix left-float issue
$($input).wrap('<div class="placeholder-container" style="display:block; position:relative; float:left; margin:0; padding:0;" />');
```

What this does is wrap all of the inputs in their own div.  This gives a nice positioning container for all the placeholder spans that get created.

As a side note: Thanks for the plugin, I think this is really cool - personally I will only be using it in force mode for consistency.  I like the method used and learned from reading the script (I'm new to javascript/jquery).  I believe with a couple modifications it also has a lot of potential to be used with the validation plugin to create "overlay" error notifications that go away on "mouse enter".  I will be dabbling with it on my end to create that effect, as it's something that a popular wordpress plugin called contact-form-7 does, and I really like it.

*took me a bit to find how to post code on these, sorry if it looks messy!

**Comment by mendrik** [comment]
thanks Fujilives, fixed my problem

**Comment by dominikwilkowski** [comment]
For this to work I had to add `'left': '0',` to `$placeholder.css()`

Thanks though.
Helped heaps

**Pull request closed without merging**
